# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
reviews:
  profile: assertive
  request_changes_workflow: true
  high_level_summary_in_walkthrough: true
  review_details: true
  fail_commit_status: true
  auto_review:
    auto_pause_after_reviewed_commits: 0
  pre_merge_checks:
    title:
      mode: error
      requirements: Title should be concise and descriptive, ideally under 200 characters
    description:
      mode: error
